### ISSUE TITLE
共通エリアで装備を変更したい

### ISSUE THREAD

**Issue by ri-yo** [ri-yo/3DS-CHEAT-MHXX#3]
完成済みのためクローズ
https://github.com/ri-yo/3DS-CHEAT-MHXX/blob/fbde7ebc3654be7861d82910ffc786dd58392bc4/%E3%82%B3%E3%83%BC%E3%83%89/%E9%9B%86%E4%BC%9A%E6%89%80/%E6%96%BD%E8%A8%AD.md?plain=1#L25-L28

**Comment by nitoloer** [comment]
検証
・ニャンタークエストでニャンターのみ受注可能になっているクエストをニャンターで受注した後、ハンターに変更しても不具合は起こらず、普通にハンターとしてクエスト出発、クリア出来ました。
